=== api-evangelist/amazon-cloudformation/json-schema/cloudformation-stack-resource-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/amazon-cloudformation/refs/heads/main/json-schema/cloudformation-stack-resource-schema.json",
  "title": "StackResource",
  "description": "StackResource schema",
  "type": "object",
  "properties": {
    "StackName": {
      "type": "string",
      "description": "The name associated with the stack."
    },
    "StackId": {
      "type": "string",
      "description": "Unique identifier of the stack."
    },
    "LogicalResourceId": {
      "type": "string",
      "description": "The logical name of the resource specified in the template."
    },
    "PhysicalResourceId": {
      "type": "string",
      "description": "The name or unique identifier of the resource."
    },
    "ResourceType": {
      "type": "string",
      "description": "Type of resource (e.g., AWS::EC2::Instance)."
    },
    "Timestamp": {
      "type": "string",
      "format": "date-time",
      "description": "Time the status was updated."
    },
    "ResourceStatus": {
      "type": "string",
      "enum": [
        "CREATE_IN_PROGRESS",
        "CREATE_FAILED",
        "CREATE_COMPLETE",
        "DELETE_IN_PROGRESS",
        "DELETE_FAILED",
        "DELETE_COMPLETE",
        "DELETE_SKIPPED",
        "UPDATE_IN_PROGRESS",
        "UPDATE_FAILED",
        "UPDATE_COMPLETE",
        "IMPORT_FAILED",
        "IMPORT_COMPLETE",
        "IMPORT_IN_PROGRESS",
        "IMPORT_ROLLBACK_IN_PROGRESS",
        "IMPORT_ROLLBACK_FAILED",
        "IMPORT_ROLLBACK_COMPLETE"
      ],
      "description": "Current status of the resource."
    },
    "ResourceStatusReason": {
      "type": "string",
      "description": "Success or failure message associated with the resource."
    },
    "Description": {
      "type": "string",
      "description": "User defined description associated with the resource."
    },
    "DriftInformation": {
      "$ref": "#/components/schemas/StackResourceDriftInformation"
    }
  },
  "required": [
    "LogicalResourceId",
    "ResourceType",
    "ResourceStatus",
    "Timestamp"
  ]
}

=== api-evangelist/amazon-cloudformation/examples/cloudformation-stack-resource-example.json
{
  "StackName": "example-resource",
  "StackId": "abc12345",
  "LogicalResourceId": "abc12345",
  "PhysicalResourceId": "abc12345",
  "ResourceType": "example-value",
  "Timestamp": "2025-03-15T14:30:00Z",
  "ResourceStatus": "CREATE_IN_PROGRESS",
  "ResourceStatusReason": "ACTIVE",
  "Description": "example-value",
  "DriftInformation": "example-value"
}
